global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['host.docker.internal:9187']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'custom_exporter'
    static_configs:
      - targets: ['host.docker.internal:8000']
